name: Build Mobile-Porter

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.4

      - name: Install and Setup Lime
        run: |
          haxelib install lime --quiet
          haxelib run lime setup -y

      - name: Install Haxelibs
        run: |
          haxelib install openfl --quiet
          haxelib install flixel --quiet
          haxelib install flixel-tools --quiet
          haxelib install flixel-addons --quiet
          haxelib install flixel-ui --quiet
          haxelib install tjson --quiet
          haxelib install hxjsonast --quiet
          haxelib install SScript --quiet
          haxelib install hxvlc --quiet

      - name: Setup Android Target
        run: |
          haxelib run lime setup android --quiet

      - name: Build android
        run: haxelib run lime build android

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Mobile-Porter-android
          path: export/release/android
          if-no-files-found: error
